services:
  db:
    container_name: mysql-db
    image: mysql:9.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: knowledge_test_db
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    container_name: knowledgeapp-api
    build:
      context: ./
      dockerfile: Deploy/Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "server=db;port=3306;database=knowledge_test_db;user=root;password=admin"
    restart: always
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    name: app-network
    external: true