// <auto-generated />
using System;
using KnowledgeApp.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnowledgeApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(KnowledgeTestDbContext))]
    [Migration("20260302170619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("faculty_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FacultyId" }, "faculty_id");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DepartmentId" }, "department_id");

                    b.ToTable("disciplines", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.DisciplineTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    b.Property<int?>("ResponsibleTeacherId")
                        .HasColumnType("int")
                        .HasColumnName("responsible_teacher_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DisciplineId" }, "discipline_id");

                    b.HasIndex(new[] { "ResponsibleTeacherId" }, "responsible_teacher_id");

                    b.ToTable("discipline_teacher", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.EmployeeRightsRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateOnly>("JobEnd")
                        .HasColumnType("date")
                        .HasColumnName("job_end");

                    b.Property<string>("JobName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("job_name");

                    b.Property<DateOnly>("JobStart")
                        .HasColumnType("date")
                        .HasColumnName("job_start");

                    b.Property<string>("StructuralDivision")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("structural_division");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("UserId");

                    b.ToTable("employee_rigths_requests");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("faculty_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("faculties", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.RecommendationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RecommendedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 3, 2, 17, 6, 19, 47, DateTimeKind.Utc).AddTicks(9191))
                        .HasColumnName("recommended_at");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("semester_id");

                    b.Property<int>("StudyGroupId")
                        .HasColumnType("int")
                        .HasColumnName("study_group_id");

                    b.Property<int?>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudyGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("recommendation_history", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AllDone")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("all_done");

                    b.Property<int?>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    b.Property<bool?>("DoneInElectronicForm")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("done_in_electronic_form");

                    b.Property<bool?>("DoneInPaperForm")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("done_in_paper_form");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_path");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_correct");

                    b.Property<string>("ResultOfAttestation")
                        .HasColumnType("text")
                        .HasColumnName("result_of_attestation");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DisciplineId" }, "discipline_id")
                        .HasDatabaseName("discipline_id1");

                    b.HasIndex(new[] { "TeacherId" }, "teacher_id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SemesterPart")
                        .HasColumnType("int")
                        .HasColumnName("semester_part");

                    b.Property<int>("SemesterYear")
                        .HasColumnType("int")
                        .HasColumnName("semester_year");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("semesters", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("statuses", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "GroupId" }, "group_id");

                    b.HasIndex(new[] { "UserId" }, "user_id");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.StudyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("group_number");

                    b.Property<int>("StudyProgramId")
                        .HasColumnType("int")
                        .HasColumnName("study_program_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "StudyProgramId" }, "study_program_id");

                    b.ToTable("study_groups", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.StudyProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CypherOfTheDirection")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cypher_of_the_direction");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DepartmentId" }, "department_id")
                        .HasDatabaseName("department_id1");

                    b.ToTable("study_programs", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Testing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int>("ReportId")
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    b.Property<string>("ResultOfTesting")
                        .HasColumnType("text")
                        .HasColumnName("result_of_testing");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scheduled_date");

                    b.Property<TimeSpan?>("ScheduledTime")
                        .HasColumnType("time")
                        .HasColumnName("scheduled_time");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("semester_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("SemesterId");

                    b.HasIndex(new[] { "DisciplineId" }, "discipline_id")
                        .HasDatabaseName("discipline_id2");

                    b.HasIndex(new[] { "GroupId" }, "group_id")
                        .HasDatabaseName("group_id1");

                    b.HasIndex(new[] { "ReportId" }, "report_id");

                    b.ToTable("testing", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("faculty_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "FacultyId" }, "faculty_id")
                        .HasDatabaseName("faculty_id1");

                    b.HasIndex(new[] { "StatusId" }, "status_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleId" }, "role_id");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .HasDatabaseName("user_id1");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Department", b =>
                {
                    b.HasOne("KnowledgeApp.Infrastructure.Entities.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("departments_ibfk_1");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Discipline", b =>
                {
                    b.HasOne("KnowledgeApp.Infrastructure.Entities.Department", "Department")
                        .WithMany("Disciplines")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("disciplines_ibfk_1");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.DisciplineTeacher", b =>
                {
                    b.HasOne("KnowledgeApp.Infrastructure.Entities.Discipline", "Discipline")
                        .WithMany("DisciplineTeachers")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("discipline_teacher_ibfk_1");

                    b.HasOne("KnowledgeApp.Infrastructure.Entities.User", "ResponsibleTeacher")
                        .WithMany("DisciplineTeachers")
                        .HasForeignKey("ResponsibleTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("discipline_teacher_ibfk_2");

                    b.Navigation("Discipline");

                    b.Navigation("ResponsibleTeacher");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.EmployeeRightsRequest", b =>
                {
                    b.HasOne("KnowledgeApp.Infrastructure.Entities.User", "User")
                        .WithMany("EmployeeRightsRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.RecommendationHistory", b =>
                {
                    b.HasOne("KnowledgeApp.Infrastructure.Entities.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeApp.Infrastructure.Entities.StudyGroup", "StudyGroup")
                        .WithMany()
                        .HasForeignKey("StudyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeApp.Infrastructure.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Semester");

                    b.Navigation("StudyGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Report", b =>
                {
                    b.HasOne("KnowledgeApp.Infrastructure.Entities.Discipline", "Discipline")
                        .WithMany("Reports")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("reports_ibfk_1");

                    b.HasOne("KnowledgeApp.Infrastructure.Entities.User", "Teacher")
                        .WithMany("Reports")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("reports_ibfk_2");

                    b.Navigation("Discipline");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Student", b =>
                {
                    b.HasOne("KnowledgeApp.Infrastructure.Entities.StudyGroup", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("students_ibfk_2");

                    b.HasOne("KnowledgeApp.Infrastructure.Entities.User", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("students_ibfk_1");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.StudyGroup", b =>
                {
                    b.HasOne("KnowledgeApp.Infrastructure.Entities.StudyProgram", "StudyProgram")
                        .WithMany("StudyGroups")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("study_groups_ibfk_1");

                    b.Navigation("StudyProgram");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.StudyProgram", b =>
                {
                    b.HasOne("KnowledgeApp.Infrastructure.Entities.Department", "Department")
                        .WithMany("StudyPrograms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("study_programs_ibfk_1");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Testing", b =>
                {
                    b.HasOne("KnowledgeApp.Infrastructure.Entities.Discipline", "Discipline")
                        .WithMany("Testings")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("testing_ibfk_2");

                    b.HasOne("KnowledgeApp.Infrastructure.Entities.StudyGroup", "Group")
                        .WithMany("Testings")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("testing_ibfk_1");

                    b.HasOne("KnowledgeApp.Infrastructure.Entities.Report", "Report")
                        .WithMany("Testings")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("testing_ibfk_4");

                    b.Navigation("Discipline");

                    b.Navigation("Group");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.User", b =>
                {
                    b.HasOne("KnowledgeApp.Infrastructure.Entities.Faculty", "Faculty")
                        .WithMany("Users")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("users_ibfk_2");

                    b.HasOne("KnowledgeApp.Infrastructure.Entities.Status", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("users_ibfk_1");

                    b.Navigation("Faculty");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.UserRole", b =>
                {
                    b.HasOne("KnowledgeApp.Infrastructure.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("user_role_ibfk_2");

                    b.HasOne("KnowledgeApp.Infrastructure.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("user_role_ibfk_1");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Department", b =>
                {
                    b.Navigation("Disciplines");

                    b.Navigation("StudyPrograms");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Discipline", b =>
                {
                    b.Navigation("DisciplineTeachers");

                    b.Navigation("Reports");

                    b.Navigation("Testings");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Faculty", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Report", b =>
                {
                    b.Navigation("Testings");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.Status", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.StudyGroup", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Testings");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.StudyProgram", b =>
                {
                    b.Navigation("StudyGroups");
                });

            modelBuilder.Entity("KnowledgeApp.Infrastructure.Entities.User", b =>
                {
                    b.Navigation("DisciplineTeachers");

                    b.Navigation("EmployeeRightsRequests");

                    b.Navigation("Reports");

                    b.Navigation("Students");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
